{
    "openapi": "3.0.0",
    "info": {
        "title": "API",
        "version": "1.0"
    },
    "paths": {
        "/token": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Retrieves bearer token for all api requests",
                "operationId": "App\\Http\\Controllers\\AuthController::GetToken",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "client_id": {
                                        "type": "string"
                                    },
                                    "client_secret": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Returns some sample category things",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Error: Bad request. When required parameters were not supplied."
                    },
                    "401": {
                        "description": "Error: Unauthorized. When supplied credentials are invalid."
                    }
                }
            }
        },
        "/enrollments": {
            "get": {
                "tags": [
                    "Enrollment"
                ],
                "summary": "Get all enrollments.",
                "description": "Returns all enrollment.",
                "operationId": "getAllEnrollments",
                "parameters": [
                    {
                        "name": "user_id_filter",
                        "in": "query",
                        "description": "Filter by user ID.",
                        "required": false,
                        "explode": true,
                        "schema": {
                            "type": "int32"
                        }
                    },
                    {
                        "name": "course_id_filter",
                        "in": "query",
                        "description": "Filter by course ID.",
                        "required": false,
                        "explode": true,
                        "schema": {
                            "type": "int32"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/enrollment_collection"
                                },
                                "examples": [
                                    {
                                        "example": 200,
                                        "summary": "",
                                        "value": [
                                            {
                                                "id": 2,
                                                "user_id": 8,
                                                "course_id": 1,
                                                "lti_course_id": 0,
                                                "last_access": 1491866005,
                                                "has_valid_access_code": false,
                                                "is_opted_out_of_assessments": false,
                                                "created_at": null
                                            },
                                            {
                                                "id": 4,
                                                "user_id": 21,
                                                "course_id": 0,
                                                "lti_course_id": 0,
                                                "last_access": 0,
                                                "has_valid_access_code": false,
                                                "is_opted_out_of_assessments": false,
                                                "created_at": null
                                            }
                                        ]
                                    }
                                ]
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "422": {
                        "description": "Unprocessable Entity"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/enrollments/{id}": {
            "get": {
                "tags": [
                    "Enrollment"
                ],
                "summary": "Get an enrollment by ID.",
                "description": "Returns an enrollment.",
                "operationId": "getEnrollmentById",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of the enrollment to return.",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/enrollment"
                                },
                                "examples": [
                                    {
                                        "example": 200,
                                        "summary": "",
                                        "value": {
                                            "id": 2,
                                            "user_id": 8,
                                            "course_id": 1,
                                            "lti_course_id": 0,
                                            "last_access": 1491866005,
                                            "has_valid_access_code": false,
                                            "is_opted_out_of_assessments": false,
                                            "created_at": null
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "422": {
                        "description": "Unprocessable Entity"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "tags": [
                    "Enrollment"
                ],
                "summary": "Update an enrollment by ID.",
                "description": "Updates an enrollment.",
                "operationId": "updateEnrollmentById",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of the enrollment to update.",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "has_valid_access_code": {
                                        "description": "Does the user have a valid access code?",
                                        "type": "boolean"
                                    },
                                    "is_opted_out_of_assessments": {
                                        "description": "Is the user opted out of assessments?",
                                        "type": "boolean"
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "has_valid_access_code": false,
                                "is_opted_out_of_assessments": false
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/enrollment"
                                },
                                "examples": [
                                    {
                                        "example": 200,
                                        "summary": "",
                                        "value": {
                                            "id": 2,
                                            "user_id": 8,
                                            "course_id": 1,
                                            "lti_course_id": 0,
                                            "last_access": 1491866005,
                                            "has_valid_access_code": false,
                                            "is_opted_out_of_assessments": false,
                                            "created_at": null
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "422": {
                        "description": "Unprocessable Entity"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/question": {
            "post": {
                "tags": [
                    "Question Display"
                ],
                "summary": "Retrieves question HTML for given question set id and seed.",
                "operationId": "App\\Http\\Controllers\\QuestionController::getQuestion",
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "example": "Bearer <token>"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "questionSetId": {
                                        "type": "int"
                                    },
                                    "ohmUniqueId": {
                                        "type": "string"
                                    },
                                    "seed": {
                                        "type": "int"
                                    },
                                    "rawScores": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "partialAttemptNumber": {
                                        "type": "array",
                                        "items": {
                                            "type": "int"
                                        }
                                    },
                                    "options": {
                                        "type": "array",
                                        "items": {
                                            "type": "int"
                                        }
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "questionSetId": 16208,
                                    "ohmUniqueId": "1fk4km8c030",
                                    "seed": 8076,
                                    "rawScores": [],
                                    "partialAttemptNumber": [],
                                    "options": {
                                        "maxtries": 1,
                                        "showansafter": "",
                                        "hidescoremarkers": false,
                                        "showallparts": "",
                                        "showans": false,
                                        "showhints": 3,
                                        "includeans": false
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "questionSetId": {
                                            "description": "Question Set Id of scored item",
                                            "type": "int"
                                        },
                                        "ohmUniqueId": {
                                            "description": "Unique Question Id of scored item",
                                            "type": "string"
                                        },
                                        "seed": {
                                            "description": "Seed of scored item",
                                            "type": "int"
                                        },
                                        "html": {
                                            "description": "Contains html for question rendering",
                                            "type": "string"
                                        },
                                        "jsparams": {
                                            "type": "object"
                                        },
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "type": "object"
                                },
                                "examples": [
                                    {
                                        "example": 200,
                                        "summary": "",
                                        "value": {
                                            "questionSetId": 123,
                                            "ohmUniqueId": "1fk4km8c030",
                                            "seed": 999,
                                            "html": "<div></div>",
                                            "jsparams": {
                                                "0": {
                                                    "tip": "Enter math expression",
                                                    "longtip": "",
                                                    "preview": 2,
                                                    "calcformat": "",
                                                    "qtype": "calculated"
                                                },
                                                "ans": [],
                                                "maxtries": [],
                                                "partatt": [],
                                                "disabled": [],
                                                "helps": []
                                            },
                                            "errors": []
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "422": {
                        "description": "Unprocessable Entity"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/questions": {
            "post": {
                "tags": [
                    "Question Display"
                ],
                "summary": "Retrieves question HTML a given list of question set ids and seeds.",
                "operationId": "App\\Http\\Controllers\\QuestionController::getAllQuestions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {}
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "422": {
                        "description": "Unprocessable Entity"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/question/score": {
            "post": {
                "tags": [
                    "Question Scoring"
                ],
                "summary": "Scores student reponse to a given question.",
                "operationId": "App\\Http\\Controllers\\QuestionController::scoreQuestion",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "questionSetId": {
                                        "type": "int"
                                    },
                                    "ohmUniqueId": {
                                        "type": "string"
                                    },
                                    "seed": {
                                        "type": "int"
                                    },
                                    "post": {
                                        "type": "array",
                                        "items": {
                                            "type": "object"
                                        }
                                    },
                                    "studentAnswers": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "studentAnswerValues": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "partAttemptNumber": {
                                        "description": "(optional)",
                                        "type": "array",
                                        "items": {
                                            "type": "int"
                                        }
                                    },
                                    "partsToScore": {
                                        "description": "(optional)",
                                        "type": "array",
                                        "items": {
                                            "type": "int"
                                        }
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "questionSetId": 16208,
                                    "ohmUniqueId": "1fk4km8c030",
                                    "seed": 8076,
                                    "post": [
                                        {
                                            "name": "qn0",
                                            "value": "1"
                                        }
                                    ],
                                    "studentAnswers": [
                                        "1"
                                    ],
                                    "studentAnswerValues": [
                                        1
                                    ],
                                    "partsToScore": [
                                        1
                                    ],
                                    "partAttemptNumber": [
                                        1
                                    ]
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "questionSetId": {
                                            "description": "Question Set Id of scored item",
                                            "type": "int"
                                        },
                                        "ohmUniqueId": {
                                            "description": "Unique Question Id of scored item",
                                            "type": "string"
                                        },
                                        "questionType": {
                                            "description": "The question type (number, multans, etc)",
                                            "type": "string"
                                        },
                                        "seed": {
                                            "description": "Seed of scored item",
                                            "type": "int"
                                        },
                                        "scores": {
                                            "description": "Contains weighted scores for given question",
                                            "type": "array",
                                            "items": {
                                                "type": "int"
                                            }
                                        },
                                        "raw": {
                                            "description": "Contains raw scores for given question",
                                            "type": "array",
                                            "items": {
                                                "type": "int"
                                            }
                                        },
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        },
                                        "allans": {
                                            "description": "True if all answer parts of question are provided otherwise false",
                                            "type": "bool"
                                        },
                                        "feedback": {
                                            "description": "Contains all correct answers",
                                            "type": "object"
                                        },
                                        "partTypes": {
                                            "description": "For multi-part questions, contains the question part types (choices, number, etc)",
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        },
                                        "correctAnswers": {
                                            "description": "Contains all correct answers",
                                            "type": "array",
                                            "items": {
                                                "type": "string|int|float"
                                            }
                                        }
                                    },
                                    "type": "object"
                                },
                                "examples": [
                                    {
                                        "example": 200,
                                        "summary": "Single part - number",
                                        "value": {
                                            "questionSetId": 3618,
                                            "ohmUniqueId": "1fk4km8c030",
                                            "questionType": "number",
                                            "seed": 482936,
                                            "scores": [
                                                1
                                            ],
                                            "raw": [
                                                1
                                            ],
                                            "errors": [],
                                            "allans": true,
                                            "feedback": {
                                                "qn0": {
                                                    "correctness": "correct",
                                                    "feedback": "Correct."
                                                }
                                            },
                                            "correctAnswers": [
                                                42
                                            ]
                                        }
                                    },
                                    {
                                        "example": 200,
                                        "summary": "Single part - multiple choice",
                                        "value": {
                                            "questionSetId": 3618,
                                            "ohmUniqueId": "1fk4km8c030",
                                            "questionType": "choices",
                                            "seed": 482936,
                                            "scores": [
                                                1
                                            ],
                                            "raw": [
                                                1
                                            ],
                                            "errors": [],
                                            "allans": true,
                                            "feedback": {
                                                "qn0-4": {
                                                    "correctness": "correct",
                                                    "feedback": "Correct."
                                                }
                                            },
                                            "correctAnswers": [
                                                "4"
                                            ]
                                        }
                                    },
                                    {
                                        "example": 200,
                                        "summary": "Single part - multiple answer",
                                        "value": {
                                            "questionSetId": 3618,
                                            "ohmUniqueId": "1fk4km8c030",
                                            "questionType": "multans",
                                            "seed": 482936,
                                            "scores": [
                                                1
                                            ],
                                            "raw": [
                                                1
                                            ],
                                            "errors": [],
                                            "allans": true,
                                            "feedback": {
                                                "qn0-1": {
                                                    "correctness": "correct",
                                                    "feedback": "Correct."
                                                },
                                                "qn0-3": {
                                                    "correctness": "correct",
                                                    "feedback": "Correct."
                                                }
                                            },
                                            "correctAnswers": [
                                                "1,3"
                                            ]
                                        }
                                    },
                                    {
                                        "example": 200,
                                        "summary": "Single part - matching",
                                        "value": {
                                            "questionSetId": 3618,
                                            "ohmUniqueId": "1fk4km8c030",
                                            "questionType": "matching",
                                            "seed": 482936,
                                            "scores": [
                                                1
                                            ],
                                            "raw": [
                                                1
                                            ],
                                            "errors": [],
                                            "allans": true,
                                            "feedback": {
                                                "qn0": {
                                                    "correctness": "correct",
                                                    "feedback": "Correct."
                                                }
                                            },
                                            "correctAnswers": [
                                                [
                                                    1,
                                                    2,
                                                    3,
                                                    4,
                                                    5,
                                                    6
                                                ]
                                            ]
                                        }
                                    },
                                    {
                                        "example": 200,
                                        "summary": "Single part - string",
                                        "value": {
                                            "questionSetId": 3618,
                                            "ohmUniqueId": "1fk4km8c030",
                                            "questionType": "string",
                                            "seed": 482936,
                                            "scores": [
                                                1
                                            ],
                                            "raw": [
                                                1
                                            ],
                                            "errors": [],
                                            "allans": true,
                                            "feedback": {
                                                "qn0": {
                                                    "correctness": "correct",
                                                    "feedback": "Correct."
                                                }
                                            },
                                            "correctAnswers": [
                                                "Cats and meows"
                                            ]
                                        }
                                    },
                                    {
                                        "example": 200,
                                        "summary": "Single part - draw",
                                        "value": {
                                            "questionSetId": 3618,
                                            "ohmUniqueId": "1fk4km8c030",
                                            "questionType": "draw",
                                            "seed": 482936,
                                            "scores": [
                                                1
                                            ],
                                            "raw": [
                                                1
                                            ],
                                            "errors": [],
                                            "allans": true,
                                            "feedback": {
                                                "qn0": {
                                                    "correctness": "correct",
                                                    "feedback": "Correct."
                                                }
                                            },
                                            "correctAnswers": [
                                                "7.65,3.583",
                                                "7.8,3.526",
                                                "7.9,3.552",
                                                "8.05,3.758",
                                                "8.05,3.313",
                                                "8.15,3.318",
                                                "8.3,2.961",
                                                "8.5,2.913",
                                                "8.65,3.253",
                                                "8.75,3.468"
                                            ]
                                        }
                                    },
                                    {
                                        "example": 200,
                                        "summary": "Single part - essay",
                                        "value": {
                                            "questionSetId": 3618,
                                            "ohmUniqueId": "1fk4km8c030",
                                            "questionType": "essay",
                                            "seed": 482936,
                                            "scores": [
                                                1
                                            ],
                                            "raw": [
                                                1
                                            ],
                                            "errors": [],
                                            "allans": true,
                                            "feedback": {
                                                "qn0": {
                                                    "correctness": "correct",
                                                    "feedback": "Sample answer: Cats are meowsome."
                                                }
                                            },
                                            "correctAnswers": [
                                                null
                                            ]
                                        }
                                    },
                                    {
                                        "example": 200,
                                        "summary": "Multi-part question",
                                        "value": {
                                            "questionSetId": 3618,
                                            "ohmUniqueId": "1fk4km8c030",
                                            "questionType": "multipart",
                                            "seed": 482936,
                                            "scores": [
                                                0.3333,
                                                0.3333,
                                                0.3333
                                            ],
                                            "raw": [
                                                1,
                                                1,
                                                1
                                            ],
                                            "errors": [],
                                            "allans": true,
                                            "feedback": {
                                                "qn1000": {
                                                    "correctness": "correct",
                                                    "feedback": "Correct."
                                                },
                                                "qn1001-0": {
                                                    "correctness": "correct",
                                                    "feedback": "Yes, apples are fruit."
                                                },
                                                "qn1001-1": {
                                                    "correctness": "correct",
                                                    "feedback": "Yes, bananas are fruit."
                                                },
                                                "qn1001-2": {
                                                    "correctness": "correct",
                                                    "feedback": "Yes, strawberries are fruit."
                                                },
                                                "qn1001-4": {
                                                    "correctness": "correct",
                                                    "feedback": "Yes, tomatoes are fruit."
                                                },
                                                "qn1002-0": {
                                                    "correctness": "correct",
                                                    "feedback": "Correct. Cats are the answer."
                                                }
                                            },
                                            "partTypes": [
                                                "number",
                                                "multans",
                                                "choices"
                                            ],
                                            "correctAnswers": [
                                                42,
                                                "0,1,2,4",
                                                "0"
                                            ]
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "422": {
                        "description": "Unprocessable Entity"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/questions/score": {
            "post": {
                "tags": [
                    "Question Scoring"
                ],
                "summary": "Scores student reponse to a given list of questions.",
                "operationId": "App\\Http\\Controllers\\QuestionController::scoreAllQuestions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {}
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "422": {
                        "description": "Unprocessable Entity"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "enrollment": {
                "properties": {
                    "id": {
                        "description": "Enrollment ID.",
                        "type": "int32"
                    },
                    "user_id": {
                        "description": "The user's ID.",
                        "type": "int32"
                    },
                    "course_id": {
                        "description": "The course ID.",
                        "type": "int32"
                    },
                    "lti_course_id": {
                        "description": "The LTI course ID.",
                        "type": "int32"
                    },
                    "last_access": {
                        "description": "The user's last access time.",
                        "type": "int32"
                    },
                    "has_valid_access_code": {
                        "description": "Does the user have a valid access code?",
                        "type": "boolean"
                    },
                    "is_opted_out_of_assessments": {
                        "description": "Is the user opted out of assessments?",
                        "type": "int32"
                    },
                    "created_at": {
                        "description": "The creation timestamp for the enrollment.",
                        "type": "int32"
                    }
                },
                "type": "object"
            },
            "enrollment_collection": {
                "properties": {
                    "": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/enrollment"
                        }
                    }
                },
                "type": "object"
            }
        }
    }
}